- Project.toml
- src/ManifoldMuseum.jl
- src/Sphere.jl
- test/runtests.jl
Major points:
* I've introduced a new function, `isapprox`.
* Sphere is in a bit better shape.
* I've added some generic tests for manifolds.
* `dot`, `exp`, `log`, `isapprox`, `norm` extend standard functions.
> Tests, isapprox and some work on Sphere

- Project.toml
- src/ManifoldMuseum.jl
- src/Sphere.jl
- test/runtests.jl
`similar_result`should take us most of the way to a decent support of automatic differentiation. Additionally, a few tests for types other than `Array{Float64}`.
> Initial pieces of support for AD

- Project.toml
- docs/make.jl
- docs/src/distributions.md
- docs/src/index.md
- docs/src/manifolds/rotations.md
- docs/src/manifolds/sphere.md
- src/Manifolds.jl
- test/metric_test.jl
- test/runtests.jl
I've changed the name to Manifolds.jl (see #19 ).
> Renaming the project to Manifolds.jl

- README.md
Should have a README, here is a (one sentence) start.
> Seed README.md

- benchmark/benchmarks.jl
- src/ProductManifold.jl
- test/product_manifold.jl
I've made some changes to allow `ProductArray`s to have views that are not statically sized (it was causing some performance issues, see #33) .
> Non-statically sized product arrays

- src/VectorBundle.jl
I've added more docs to `VectorBundle`. Looking at it again, I've noticed that projections a bit sloppily implemented and vector transport needs to be improved but it doesn't look urgent.
> more docs for vector bundles

- docs/make.jl
e.g. this PR's docs will be available at https://julianlsolvers.github.io/Manifolds.jl/previews/PR59/
> Build preview docs for PRs

- .gitignore
- Manifest.toml
- Project.toml
- src/CholeskySpace.jl
- src/Euclidean.jl
- src/FixedRankMatrices.jl
- src/Grassmann.jl
- src/Manifolds.jl
- src/Stiefel.jl
- src/Symmetric.jl
- test/euclidean.jl
- test/fixed_rank.jl
- test/grassmann.jl
- test/power_manifold.jl
- test/rotations.jl
- test/runtests.jl
- test/stiefel.jl
- test/symmetric.jl
- test/utils.jl
> introduce concrete Field type for Manifolds

- .travis.yml
- Manifest.toml
- Project.toml
- appveyor.yml
- docs/Project.toml
- src/Grassmann.jl
- src/Stiefel.jl
- test/cholesky_space.jl
- test/euclidean.jl
- test/grassmann.jl
- test/groups/rotation_action.jl
- test/groups/translation_action.jl
- test/hyperbolic.jl
- test/metric.jl
- test/product_manifold.jl
- test/rotations.jl
- test/sphere.jl
- test/stiefel.jl
- test/symmetric.jl
- test/symmetric_positive_definite.jl
- test/utils.jl
- test/vector_bundle.jl
Following https://github.com/JuliaNLSolvers/ManifoldsBase.jl/pull/18, don't constrain inner products for complex manifolds to be real.
> Use Hermitian inner product and reduce number of tests

- .travis.yml
> Build documentation with Travis again

- Manifest.toml
- Project.toml
- src/Manifolds.jl
- src/statistics.jl
> Fixes #116

- .github/workflows/ci-nightly.yml
- .github/workflows/ci.yml
- .github/workflows/documenter.yml
> Allow nightly failures on GitHub Actions

- Project.toml
> Lower-bound Distributions at 0.22.6

- Project.toml
- src/manifolds/PowerManifold.jl
- test/power_manifold.jl
> Modified constructor of PowerManifold

- Project.toml
- src/manifolds/PowerManifold.jl
- test/power_manifold.jl
Solves a part of #180 . This makes broadcasting work.
> view for AbstractPowerManifold

- src/Manifolds.jl
- src/manifolds/Euclidean.jl
- src/manifolds/Hyperbolic.jl
- src/statistics.jl
- test/hyperbolic.jl
- test/statistics.jl
I've made a simple implementation of the extrinsic mean estimator. Resolves #77 .
> Extrinsic mean estimator

- src/manifolds/Stiefel.jl
- test/fixed_rank.jl
- test/power_manifold.jl
- test/product_manifold.jl
- test/runtests.jl
- test/utils.jl
- test/vector_bundle.jl
> Printing fixes for Julia 1.6

- Project.toml
- src/statistics.jl
- test/statistics.jl
Works on #184, including a test and some documentation.
> an extrinsic median estimation.

- Project.toml
- src/manifolds/PowerManifold.jl
- test/power_manifold.jl
Just two new methods :slightly_smiling_face: .
> Projection on power manifolds

- .github/workflows/documenter.yml
- docs/Project.toml
- docs/make.jl
- src/SizedAbstractArray.jl
- src/manifolds/Stiefel.jl
- src/tests/tests_general.jl
- test/centered_matrices.jl
- test/elliptope.jl
- test/fixed_rank.jl
- test/grassmann.jl
- test/metric.jl
- test/oblique.jl
- test/skewsymmetric.jl
- test/spectrahedron.jl
- test/stiefel.jl
Let's first test that this does currently not deploy (trying to solve #148).
We should maybe at some point also delete old PRs preview docs.
> Conditional deploy docs.

- Project.toml
- docs/src/misc/internals.md
- src/manifolds/Stiefel.jl
- src/utils.jl
- test/stiefel.jl
I just saw an idea how to construct this. I still have to add tests, but feel free to already look at the code.
> Introduce a basis for tangent spaces of Stiefel

- Project.toml
- src/tests/tests_general.jl
- src/tests/tests_group.jl
I've added a couple of new tolerances that I need for https://github.com/JuliaManifolds/FunManifolds.jl/pull/10 .
> Some new test tolerances

- src/groups/group_action.jl
- src/manifolds/Euclidean.jl
- src/manifolds/VectorBundle.jl
- test/euclidean.jl
- test/vector_bundle.jl
A few more things I need for https://github.com/JuliaManifolds/FunManifolds.jl/pull/10 : a bugfix and some embeddings.
> Center of orbit fix and some embeddings

- Project.toml
- src/groups/group.jl
- src/manifolds/Rotations.jl
- test/groups/special_orthogonal.jl
Related to https://github.com/JuliaManifolds/Manifolds.jl/pull/249#issuecomment-725789794 . This seems so mostly work but there are some failures with `get_vector` and `get_coordinates` (it looks like there is some problem with dispatch transparency). @kellertuer , could you help with that?
> Some work on making groups embedded

- src/manifolds/VectorBundle.jl
- src/product_representations.jl
- test/product_manifold.jl
- test/vector_bundle.jl
I've added `ParallelTransport` for tangent bundles, and two minor things discussed with @kellertuer .
> Tangent bundle parallel transport and maintenance

- .github/workflows/TagBot.yml
See https://discourse.julialang.org/t/ann-required-updates-to-tagbot-yml/49249 for details.
> Update to TagBot.yml

- docs/Project.toml
Forgotten in https://github.com/JuliaManifolds/Manifolds.jl/pull/274
> Bump ManifoldsBase.jl compatibility in docs project

- .github/workflows/IntegrationTest.yml
adopted (or in other words mainly copied) from  https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/105.
This resolves #326
> Adds an integration test with Manopt

- .github/workflows/ci.yml
- test/runtests.jl
Utility tests keep failing at random so to avoid that problem I've set a seed for random number generator. Additionally I've added testing on Julia 1.6-RC.
> Deterministic tests of utilities and testing on Julia 1.6-RC

- Project.toml
- src/Manifolds.jl
- src/manifolds/Hyperbolic.jl
- test/hyperbolic.jl
- test/runtests.jl
by passing on the neccessary functions to the value field. This addresses #10 for the hyperbolic types.
> introduce broadcasting for all _HyperbolicTypes

- test/groups/special_euclidean.jl
> Small fix on Rotations(2) test semantics

- .github/workflows/CompatHelper.yml
This will fix the issue you are having with duplicated CompatHelper PRs.
> Update CompatHelper to the latest recommended configuration

- CITATION.bib
- README.md
- docs/src/index.md
We can also add the arXiv badge and code block for the arXiv to ManifoldsBase.
> Update index and readme to refer to the arXiv preprint.

- src/manifolds/Elliptope.jl
- test/elliptope.jl
> Fix projection which had a wrong normalisation factor.

- Project.toml
- src/groups/group.jl
- src/statistics.jl
- test/statistics.jl
A small generalization of the estimator written here: https://github.com/JuliaRobotics/IncrementalInference.jl/issues/1336 (thanks @Affie !)
> Covariance estimation

- Project.toml
- docs/make.jl
- src/manifolds/ProductManifold.jl
Solves the second part of #412 .
> Faster `get_vector! ` on `ProductManifold`

- Project.toml
- src/manifolds/Euclidean.jl
- src/manifolds/ProductManifold.jl
- src/product_representations.jl
> Even faster `get_vector` and some other

- Project.toml
- assets/projection_illustration.jl
- assets/retraction_illustration.jl
- src/distributions.jl
- src/manifolds/ProductManifold.jl
- src/projected_distribution.jl
- test/manifolds/product_manifold.jl
- test/manifolds/sphere.jl
> Fix projected distribution with multiple points

- Project.toml
- src/manifolds/SymmetricPositiveDefiniteLinearAffine.jl
- test/manifolds/symmetric_positive_definite.jl
This will fix #457.
Main Changes: We have to take the Eigenvectors of p^-1/2 V p^-1/2 (if V is the frame direction, V = I for ONB so then just p^-1) and the ONB vectors have to be post multiplied with p^1/2 * Xi * p^1/2
But we still need to adapt get_vector and get_coordinates since they are nor much more complicated.
> fix Tangent ONB and DiagONB and add a Test.

- Project.toml
- src/manifolds/Rotations.jl
- test/manifolds/rotations.jl
Implementation from #453 (thanks @const-ae!)
> Diagonalizing ONB for rotations

- src/manifolds/VectorBundle.jl
- test/manifolds/vector_bundle.jl
A small extension to make `VectorBundle` a bit more versatile.
> ArrayPartition for VectorBundle

- Project.toml
- src/manifolds/Circle.jl
- src/manifolds/Euclidean.jl
- src/manifolds/HyperbolicHyperboloid.jl
- src/manifolds/PositiveNumbers.jl
- src/manifolds/ProjectiveSpace.jl
- src/manifolds/Rotations.jl
- src/tests/tests_general.jl
- test/manifolds/circle.jl
- test/manifolds/positive_numbers.jl
This PR fixes rotations manifold so that projections actually change the representation of tangent vectors. Also a couple of related changes.
> Projections change representation

- Project.toml
- src/groups/special_orthogonal.jl
- test/groups/special_orthogonal.jl
Just to make it faster and more robust.
> Special case exp_lie and log_lie for SO(2)

- Project.toml
- src/groups/product_group.jl
- src/groups/semidirect_product_group.jl
- src/groups/special_euclidean.jl
- test/ambiguities.jl
- test/groups/product_group.jl
- test/groups/semidirect_product_group.jl
- test/groups/special_euclidean.jl
> getindex and setindex! for product groups

- Project.toml
- src/groups/circle_group.jl
- test/ambiguities.jl
- test/groups/circle_group.jl
- test/groups/groups_general.jl
that was left from the time where we had implicit power manifold groups. 
Resolves #512.
> Fix an ambiguity from RealCircleGroup

- Project.toml
- src/manifolds/HyperbolicHyperboloid.jl
- src/manifolds/Lorentz.jl
One more improvement to `minkowski_metric`.
> Faster minkowski_metric for large vectors.

- .github/workflows/CompatHelper.yml
I am not yet sure how to test this on a PR; since this upgrades recurring GHA.
> bump compatHelper GHA

- Project.toml
- src/manifolds/Stiefel.jl
- src/manifolds/StiefelEuclideanMetric.jl
- test/manifolds/stiefel.jl
Resolves a part of https://github.com/JuliaManifolds/Manopt.jl/discussions/153 .
> Set default retraction and inverse retraction of Stiefel

- Project.toml
- src/manifolds/ProductManifold.jl
- test/manifolds/product_manifold.jl
@kellertuer second PR with Riemann tensor :slightly_smiling_face:
> Riemann tensor on product manifold

- Project.toml
- src/manifolds/PositiveNumbers.jl
- test/manifolds/positive_numbers.jl
A small extension that turned out to be useful for a test of https://github.com/JuliaManifolds/Manopt.jl/pull/167 .
> Coordinates and random vectors on PositiveNumbers and arrays

- .github/dependabot.yml
- .github/workflows/ci.yml
- test/manifolds/symplecticstiefel.jl
- test/runtests.jl
See https://github.com/JuliaManifolds/ManifoldsBase.jl/pull/149 .
> enable dependabot for GitHub actions

- Project.toml
- src/product_representations.jl
- test/manifolds/product_manifold.jl
Fixes the issue noticed in https://github.com/JuliaManifolds/Manopt.jl/pull/256 (sorry, I've overlooked that corner case).
> Fix ArrayPartition allocation with (number) eltype

- src/manifolds/ProbabilitySimplex.jl
- test/manifolds/probability_simplex.jl
This fixes the issue noticed in https://github.com/JuliaManifolds/Manifolds.jl/pull/604#issuecomment-1589290857 (and also projection).
> Fix change_metric, change_representer and project for ProbabilitySimplex

- NEWS.md
- Project.toml
- src/manifolds/Euclidean.jl
- test/manifolds/euclidean.jl
See https://github.com/JuliaManifolds/Manopt.jl/pull/335#issuecomment-1870372162 .
> Fix 0-index Euclidean just like Circle

- NEWS.md
- Project.toml
- src/groups/GroupManifold.jl
- src/groups/group.jl
- src/groups/translation_group.jl
- test/groups/translation_group.jl
Reported here: https://github.com/JuliaRobotics/IncrementalInference.jl/issues/1811 .
> Fix `var` for `TranslationGroup`

- .github/workflows/ci.yml
- NEWS.md
- Project.toml
- test/groups/special_euclidean.jl
- test/manifolds/circle.jl
- test/manifolds/multinomial_spd.jl
Let's also see if we can test on Julia 1.11-beta.
> Bump version to 0.9.19

- NEWS.md
- src/groups/group.jl
> Documentation clarification

- src/manifolds/SymplecticGrassmannStiefel.jl
- src/manifolds/SymplecticStiefel.jl
...from `q, p, X` to `X, p, q`
> Fix argument order for inverse_retract! for SymplecticGrassmann and SymplecticStiefel

- src/manifolds/HyperbolicHyperboloid.jl
> Tiny typos

- NEWS.md
- docs/src/manifolds/shapespace.md
- src/manifolds/DeterminantOneMatrices.jl
- test/manifolds/determinant_one_matrices.jl
Due to copy paste one error message was wrong and even quite misleading. This fix can still wait for the nest release.
> fix a misleading error message.

- NEWS.md
- Project.toml
- src/groups/general_linear.jl
- test/groups/general_linear.jl
Resolves the issue spotted in https://github.com/JuliaManifolds/Manopt.jl/issues/473 .
> Fix in-place exp! for GeneralLinear

- NEWS.md
- Project.toml
- src/utils.jl
- test/differentiation.jl
I missed another NaN answer in the previous PR.
> Next part of ForwardDiff.jl v1 compatibility
