- src/ManifoldMuseum.jl
- src/Sphere.jl
- test/runtests.jl
I've made a few new changes:
* `isapprox` for tangent vectors,
* scaling argument for `exp` and `retract`,
* some docs,
* new tests for tangent vectors,
* `log`, `exp` and `isapprox` are not explicitly exported (they don't have to be).
> Scaling argument for exp and retract, docs, tangent vector tests

- src/ProjectedDistribution.jl
- src/Rotations.jl
- test/euclidean.jl
- test/product_manifold.jl
- test/rotations.jl
- test/sphere.jl
- test/utils.jl
I've fixed mutating `rand!` for most distributions and the `Array` type. `rand!` doesn't seem to be compatible with `MArray` and `SizedArray` though.
> Some fixes for mutating rand!

- Project.toml
- src/Manifolds.jl
- src/Metric.jl
- src/forward_diff.jl
- src/ode.jl
- test/metric_test.jl
As discussed in #35, by far most of `Manifold`'s long load time (>20s!) is due to `OrdinaryDiffEq` as a dependency. Since `OrdinaryDiffEq` and `ForwardDiff` are only necessary for `MetricManifold` defaults, this PR makes them optional dependencies. On my machine running Julia 1.3 rc2, `Manifold`'s new load time is ~2s.
> Make OrdinaryDiffEq and ForwardDiff optional

- benchmark/benchmarks.jl
- src/SymmetricPositiveDefinite.jl
Nothing major but demonstrates that in many cases `MMatrix` is faster than `Matrix`.
```
| `["manifolds", "SPD manifold SymmetricPositiveDef, type Array{Float64,2}", "2 * tv1 + 3 * tv2"]`                             | 212.000 ns (5%) |         |  480 bytes (1%) |           3 |
| `["manifolds", "SPD manifold SymmetricPositiveDef, type Array{Float64,2}", "distance"]`                                      |   2.915 μs (5%) |         |   5.66 KiB (1%) |          21 |
| `["manifolds", "SPD manifold SymmetricPositiveDef, type Array{Float64,2}", "exp!"]`                                          |   5.023 μs (5%) |         |   6.22 KiB (1%) |          43 |
| `["manifolds", "SPD manifold SymmetricPositiveDef, type Array{Float64,2}", "exp"]`                                           |   5.071 μs …
```
> benchmarks updated for recent changes

- .travis.yml
Currently, Travis runs on the PR rebased onto master ("pr") and on the branch itself ("push"). The former is what appveyor does. This PR removes the latter case, effectively halving the number of Travis builds.
The pros are obvious. The downsides happen when PRs have merge conflicts that prevent the rebase; then Travis will not run, same as appveyor.
> Don't run Travis on feature branches

- .travis.yml
- appveyor.yml
- src/manifolds/MetricManifold.jl
- test/metric.jl
Julia 1.4.0-rc1 is now out. In addition to the nightly (which is now on Julia 1.5), we should start testing explicitly against 1.4. To keep our test suite roughly the same runtime, I've removed testing against Julia 1.2, since it is not a long term support release.
> Start testing Julia 1.4, stop testing Julia 1.2, and remove ODE support for Julia 1.0

- src/groups/group.jl
- src/groups/semidirect_product_group.jl
- src/manifolds/Circle.jl
- src/manifolds/GeneralizedGrassmann.jl
- src/manifolds/Grassmann.jl
- src/manifolds/Hyperbolic.jl
- src/manifolds/PowerManifold.jl
- src/manifolds/ProductManifold.jl
- src/manifolds/Rotations.jl
- src/manifolds/Sphere.jl
- src/manifolds/SymmetricPositiveDefinite.jl
- src/manifolds/VectorBundle.jl
JuliaFormatter v0.4.1 fixed the issue we had with `@invoke_maker` calls always being reformatted, so this updates the final format (and _should_ make the Format workflow pass).
> Reformat `@invoke_maker` calls

- Project.toml
Temporarily upper-bound FiniteDifferences until https://github.com/JuliaDiff/FiniteDifferences.jl/issues/67 is resolved. I don't think this should be part of a release, just so our CI passes.
> Upper-bound FiniteDifferences

- src/manifolds/Stiefel.jl
Do simplifications of `project!` method discussed in #141 and mentioned in #142.
Key idea is that `s.U' * s.U` in the previous implementation should (up to numerical issues) be approximately `I` in which case the remaining code simplifies.
> Simplify project! for Stiefel

- src/Manifolds.jl
- src/manifolds/Grassmann.jl
- src/manifolds/Stiefel.jl
- test/grassmann.jl
- test/stiefel.jl
Fixes #141 
Added `uniform_distribution` for `Stiefel` following the example for `Sphere`. In order to fit within the `ProjectedPointDistribution` framework, created a thin wrapper around `randn` called (for now) `RandnMatrix`. Happy to iterate on this, not sure if it's the best way!
Some todos:
+ [x] ~~(maybe) simplify implementation of `project!(M::Stiefel, q, p)` to eliminate (potentially unnecessary) eigendecomposition of U'U = I (up to numerical errors).~~ (new pr: #153)
+ [x] ~~complex-valued case? (currently not handled)~~ (new issue: #152)
+ [x] Grassmann (should be easy once we're happy with the Stiefel)
+ [x] ~~(maybe) tackle generalized Stiefel/Grassmann~~ (new issue: #152)
+ [x] tests (will likely follow whatever is done for `Sphere`)
> Add uniform distribution for Stiefel/Grassmann, fixes #141

- docs/make.jl
- docs/src/tutorials/manifold.md
- src/manifolds/Sphere.jl
My aim is to maybe slowly extend this and write more tutorials in forthcoming PRs.
> Proposes a tutorial on how to implement a manifold

- Project.toml
- src/manifolds/FixedRankMatrices.jl
- test/fixed_rank.jl
Hi,
I think there's a small bug in the `check_manifold_point` method for `FixedRankMatrices`. I think these simple changes are enough to fit the manifold definition exactly
The error can be retrieved by doing
```julia
M = FixedRankMatrices{5, 6, 3, ℝ}()
x = SVDMPoint(rand(5, 6), 3)
check_manifold_point(M, x)
```
> Bug in check_manifold_point for FixedRankMatrices

- .github/workflows/documenter.yml
Apparently the releases/v1 branch of docdeploy is outdated. I'm also hoping this resolves the errors we're getting for that action.
> Switch to docdeploy action v1

- Project.toml
This pull request changes the compat entry for the `Distributions` package from `0.22.6, 0.23` to `0.22.6, 0.23, 0.24`.
This keeps the compat entries for earlier versions.
Note: I have not tested your package with this new compat entry. It is your responsibility to make sure that your package tests pass before you merge this pull request.
> CompatHelper: bump compat for "Distributions" to "0.24"

- test/fixed_rank.jl
- test/power_manifold.jl
- test/product_manifold.jl
- test/runtests.jl
Let's try making tests pass on Julia 1.6 nightly. For now I'm ignoring the issue about ambiguities.
> Some fixes for Julia 1.6 nightly

- docs/src/manifolds/stiefel.md
- src/Manifolds.jl
- src/manifolds/Stiefel.jl
- test/stiefel.jl
adds a pade approximation based retraction as well as its special case the caley retraction – as well as a corresponding vector transport.
We could check whether a `VectorTransport` that stems from a retraction (its differentiation) is a reasonable own type.
> Caley Retraction

- src/manifolds/PowerManifold.jl
- test/power_manifold.jl
This case was not documented that way, so to be precise this might be a breaking PR (comments welcome). This fixes the following situation:
Imagine you have a `N = PowerManifold(M,n)` (maybe nested, but not required to be)
and you form a `O = PowerManifold(N, NestedPowerRepresentation(), m)`
I would expect that the nested-ness of `O` specifies, that elements are vectors of length `m` (or arrays if `m` is not a number but a tuple), since we assume nestedness.
Previously this was not the case an `O` would be a `PowerManifold(M,n,m)`, which one would not expect.
Now this is documented to work as described above, using a new constructor and its test is also added.
> Fixes Nested PowerManifold of a PowerManifold to not concatenate sizes.

- .JuliaFormatter.toml
- .github/workflows/format.yml
This also makes running formatter locally easier because you don't have to pass the style anymore.
If this is ok, I would also apply this change to our other packages (just doing one commit to master).
> Move formatter config to configuration file

- docs/src/manifolds/vector_bundle.md
- src/manifolds/VectorBundle.jl
- test/runtests.jl
- test/vector_bundle.jl
For https://github.com/JuliaManifolds/FunManifolds.jl/pull/10 I need a way to represent tangent space at a point as a manifold (for example for curves in the tangent space) so here I re-use `VectorSpaceAtPoint` for that.
Does this look reasonable?
> Vector space manifold

- src/manifolds/Oblique.jl
- src/manifolds/SymmetricPositiveDefiniteLinearAffine.jl
- test/oblique.jl
I think we should introduce `ParallelTransport`(and all other transports) a Manifold obtains from it “child” within an `AbstractPowerManifold` i.e. wrapping the `PowerTransportMethod`for ease of use for the user.
This PR introduces this for the Oblique manifold but surely we can check for more manifolds where this would be nice.
> Introduce ParallelTransport for Oblique

- Project.toml
- src/manifolds/VectorBundle.jl
- src/product_representations.jl
- test/product_manifold.jl
> Type stabilization of ProductArray

- src/groups/group.jl
- test/groups/groups_general.jl
I think this was wrongly defined in #251 .
> Fix transparency of get_vector! and get_coordinates! for AbstractGroupManifold

- Project.toml
- src/manifolds/SymmetricPositiveDefiniteLinearAffine.jl
- src/manifolds/VectorBundle.jl
This is just a small bug fix PR.
We noticed that `cholesky` gets very unstable when the matrix is not symmetric (and one disables the checks). With an added `Symmetric` it works fine and is accurate again.
Furthermore for tangent bundle the inner was not working. A tangent vector to the tangent bundle is basically two tangent vectors, so the second (tangent components) inner has to also use the base-base point as inner. @mateuszbaran can you check whether this also holds for the vector bundle? Then we could unify both implementations again.
> Stabilize SPD distance and a small fix to TangentBundle

- docs/src/manifolds/vector_bundle.md
- src/Manifolds.jl
- src/manifolds/VectorBundle.jl
- test/vector_bundle.jl
This PR aims to provide
* `p[M, :base]`
* `p[M, :Tangen]`and `p[M, :cotangent]`, respectively,
but today seems to be the case of ideas, that are too clever for me.
* ProductRepr and ProductArray are only loaded after bundle and I am not sure why, but I can't change the order just now
* I am not sure a `setindex!`would work with `ProductRepr`
* I am not sure a `ProductArray` is useful for (co)tangent bundles, since I cound find no documentation on how to construct/use `ProductArray`s (only that `ProductRepr`which I used until now may be slower than the thing I can't construct).
> Semantic access to points on tangent and cotangent bundle

- Project.toml
- src/manifolds/Euclidean.jl
- src/manifolds/Oblique.jl
- src/manifolds/PowerManifold.jl
- src/manifolds/Sphere.jl
- test/euclidean.jl
- test/oblique.jl
- test/power_manifold.jl
- test/statistics.jl
Provides a thorough distinction between 1-element arrays (`Euclidean(1)`) and immutable points/numbers (`Euclidean()`). This resolves #327.
> Euclidean numbers

- Project.toml
- src/manifolds/Rotations.jl
- src/manifolds/SkewSymmetric.jl
This PR makes several non-breaking changes to `SkewSymmetricMatrices` and also reuses its functionality when possible for the tangent vectors of `Rotations`.
> Updates to SkewSymmetricMatrices

- Project.toml
- src/manifolds/ProductManifold.jl
- test/product_manifold.jl
While workingg on JuliaManifolds/Manopt.jl#79 I noticed that an `getindex` is nice when working with manifolds, so similar to accessing `ProductRepr` as `x[M,1]` not accessing the first component of a product manifold `M` is just `M[1]`.
> A getindex for product manifold

- Project.toml
This pull request changes the compat entry for the `Distributions` package from `0.22.6, 0.23, 0.24` to `0.22.6, 0.23, 0.24, 0.25`.
This keeps the compat entries for earlier versions.
Note: I have not tested your package with this new compat entry. It is your responsibility to make sure that your package tests pass before you merge this pull request.
> CompatHelper: bump compat for "Distributions" to "0.25"

- Project.toml
- src/Manifolds.jl
- src/manifolds/Euclidean.jl
- src/manifolds/MetricManifold.jl
- test/euclidean.jl
- test/metric.jl
@jlumpe pointed out that
```
using Manifolds
M = MetricManifold(Euclidean(3), EuclideanMetric())
christoffel_symbols_first(M, zeros(3))
```
Throws an error, that `christoffel_symbols_first not implemented on Euclidean(3; field = ℝ)...`.
I was surprised by that and dived a little bit into our dispatch system for Christoffel symbols and their Jacobians.
I think I found the culprit.
In the original code the functions `christoffel_symbols_first`, `christoffel_symbols_second`,  `christoffel_symbols_second_jacobian` and `local_metric_jacobian` where introduced as transparent functions in our decorator system. This meant the following
1. the functions acted completely transparent when called with another decorator (group manifold for example)
2. the original implementation works for non-default …
> Fix behaviour of christioffel symbol functions and related Jacobians 

- src/product_representations.jl
- test/runtests.jl
As discussed in https://github.com/JuliaManifolds/Manifolds.jl/pull/366#discussion_r640132557 .
> Deprecate ProductArray

- Project.toml
- docs/src/features/atlases.md
- docs/src/misc/notation.md
- src/Manifolds.jl
- src/atlases.jl
- src/manifolds/Sphere.jl
- src/tests/tests_general.jl
- test/power_manifold.jl
- test/product_manifold.jl
- test/sphere.jl
I renamed the function according to our discussion (closes #370).
I also added a few more details to the docs concerning atlasess.
Especially, since I had to think about that for a moment myself, I added how charts and parametrizations look like for the `RetractionAtlas`.
I noticed a small caveat, that I currently did not add, since it might really be just a technical remark.
In the `transition_map`, if one chooses `A_from` and `A_to` such that their union is not an atlas, i.e. they are not compatible, then they represent a different structure and in the new parametrisation – informally said – smoothness on `M` might be different.
> rename `get_point_coordinates` to `get_parameters`

- .github/workflows/format.yml
- test/runtests.jl
This PR adapts DynamicPPL's convenient [format action](https://github.com/TuringLang/DynamicPPL.jl/blob/master/.github/workflows/Format.yml), which uses the diff generated from running the formatter to review the code and suggest formatting changes, which is more more handy than just telling the author to go run JuliaFormatter.
> Make format action suggest formatting changes

- Project.toml
- src/manifolds/SymmetricPositiveDefiniteLinearAffine.jl
By definition symmetric positive definite matrices have positive eigenvalues. Numerical errors may result in infinitesimal negative eigenvalues being computed, resulting in DomainErrors when the sqrt or log of the eigenvalue is calculated.
This change replaces any negative eigenvalues with the smallest positive value to ensure that the sqrt is successful.
This makes it the user's responsibility to ensure that input arguments are valid SPDs before
passing.
This is similar logic to https://github.com/JuliaManifolds/ManifoldsBase.jl/pull/68
> Ensure eigenvalues are positive in SPD matrices

- .github/workflows/ci.yml
- Project.toml
- src/Manifolds.jl
- src/manifolds/StiefelCanonicalMetric.jl
- test/runtests.jl
- test/stiefel.jl
Refactor the one approximate algorithm for a log we have to be an approximate log struct (subtype of approximate inverse retraction).
We should discuss
* backwards compatibility to the old variant of the log with keywords (currently this is the case), but we could also deprecate this already
* the docs are currently in the Stiefel manifold since (similar to PadeRetraction) that is the only manifold where this occurs. We should move it to base when we have a second manifold that needs this (and at that time also add the analogue for exp).
> Introduce an ApproximateLogarithmicMap.

- Project.toml
- src/manifolds/ProductManifold.jl
- test/product_manifold.jl
This avoids (a) the necessity to overwrite the nonmutatig function and (b) implicitly turns any plain (non-`ProductVectorTransport` type) into a `ProductVectorTransportType` with copies of that type inside.
Partly resolves #384
> introduce a vector transport for plain types on ProductManifold

- Project.toml
- src/manifolds/Rotations.jl
- test/rotations.jl
So the `exp!` returned a wrong result when called as `exp!(M, p, p X)` due to this side effect. Also adds a test for this.
> Fixes a bug, that occured when calling `exp!(Rotations(2), p, p, X)` since `q=p` was modified.

- docs/make.jl
Thanks to https://github.com/ranocha/SummationByPartsOperators.jl/pull/110 and https://github.com/JuliaDocs/Documenter.jl/issues/1620 I learned how to fix the “Edit on GitHub” link for pages that we include ourselves.
> Fix the Contribution link on the documentation page.

- Project.toml
- src/groups/special_euclidean.jl
- src/manifolds/ProductManifold.jl
- src/tests/tests_group.jl
- test/groups/special_euclidean.jl
- test/manifolds/product_manifold.jl
This resolves #349 – by throwing an error when one enters product manifolds with wrong encapsulating types (i.e. neither ProductRepr nor ProductArray). We can loosen this once we also allow tuples or arrays in there (would require rewriting accessing the components).
> Tightens tests for points/vectors on product manifolds

- Project.toml
- src/groups/semidirect_product_group.jl
Problem reported in #408 . `ProductArray` is deprecated so it shouldn't be returned by default.
> Make `allocate_result(G::SemidirectProductGroup, ::typeof(identity_element))` return `ProductRepr` instead of `ProductArray`

- Project.toml
- src/Manifolds.jl
- src/groups/semidirect_product_group.jl
- src/groups/special_euclidean.jl
- src/manifolds/ProductManifold.jl
- src/manifolds/Sphere.jl
- src/product_representations.jl
- test/ambiguities.jl
- test/groups/special_euclidean.jl
- test/manifolds/product_manifold.jl
This should make `ArrayPartition` work with `ProductManifold`. Some random points:
1. `println(io, "$(T()) for a product manifold")` doesn't work for `DiagonalizingOrthonormalBasis`, so I changed that.
2. I have no idea why `Ξ = [convert(T, V[:, i]) for i in 1:n]` worked without a conversion before but it doesn't now (specifically, without conversion `push!`ing vectors in `get_vectors` of `ProductManifold` fails:
```julia
function get_vectors(
M::ProductManifold,
p::ArrayPartition,
B::CachedBasis{𝔽,<:AbstractBasis{𝔽},<:ProductBasisData},
) where {𝔽}
```
> `ArrayPartition` as a product manifold representation

- Project.toml
- src/manifolds/FixedRankMatrices.jl
- test/manifolds/fixed_rank.jl
This is just a small PR introducing vector transport by projection on fixed Rank matrices. Note that it embeds the UMTTVector in the embedding to project, this is necessary since UMTTVector is stored in a reduced form (i.e. for X at p the data from p is required to get the original matrix to represent X).
> Introduces vector transport by projection on FixedRankMatrices.

- .zenodo.json
- Project.toml
- docs/src/manifolds/rotations.md
- src/manifolds/Rotations.jl
- test/manifolds/rotations.jl
Here is my first draft of the `embed!` function for rotation manifolds as discussed on the slack channel.
I also included some documentation, but no unit tests, because I am still struggling a bit with package development in Julia.
> Add embed! function for Rotation manifolds

- assets/projection_illustration.jl
- assets/retraction_illustration.jl
- src/Manifolds.jl
- src/manifolds/ProductManifold.jl
- test/manifolds/product_manifold.jl
A small fix so that `get_coordinates` doesn't return `ArrayPartition` back.
> Fix `allocate_coordinates` for `ArrayPartition`

- Project.toml
- docs/src/features/differentiation.md
- src/Manifolds.jl
- src/differentiation/embedded_diff.jl
- test/differentiation.jl
Solves #454. 
The `EmbeddedBackend´ contains the gradient (derivative, jacobian) of a function $f$ defined on a manifold that describe its gradient (derivative, jacobian) as a function extended into the embedding. Similar t Euclidean tools available they hence return Euclidean gradients (derivatives, Jacobins) that have to be converted.
* We should find a way to maybe also introduce mutating variants 
* Is the design ok this way?
* Yes, documentation is missing.
> Introduce EmbeddedBackend

- Project.toml
- src/manifolds/SymmetricPositiveDefiniteBuresWasserstein.jl
- src/manifolds/SymmetricPositiveDefiniteGeneralizedBuresWasserstein.jl
When using the new BuresWasserstein we noticed that the log somethimes returned complex values. This PR avoids the complex values (as numerical artefacts) by passing symmetrized matrices to `sqrt`.
> Stabilise log for BW and GBW

- Project.toml
- src/groups/translation_group.jl
- test/groups/translation_group.jl
To not fall back to the ODE solver (just because Euclidean is a `MetricManifold` but the ExplicitDecorator comes later).
Fixes #483.
The one thing to discuss here is, whether this should be done for all group manifolds (i.e. to have a special just-fallback-exp!)?
What do you think @mateuszbaran ?
> Fix exp! fallback on Translation group

- Project.toml
- src/manifolds/PowerManifold.jl
- test/manifolds/power_manifold.jl
Adds allocation methods for some nested replacing power manifold cases. Follow up on https://github.com/JuliaManifolds/ManifoldsBase.jl/pull/116 . Solves next part of #497 .
> Follow up on manifold-specific allocation

- src/manifolds/GeneralUnitaryMatrices.jl
Hi there, I found what I believe to be a small typo in the doc string of the `project!` method for general unitary matrices, as the implementation projects `p \ X` onto the skew-symmetric matrices, not `p * X`.
> Update docstring to match implementation

- Project.toml
- src/manifolds/FixedRankMatrices.jl
- test/manifolds/fixed_rank.jl
On fixed rank matrices, we do have a retraction, an inverse retraction and a vector transport. This PR introduces them as defaults.
> Introduce default methods on FR

- Project.toml
- src/manifolds/GrassmannStiefel.jl
- src/manifolds/StiefelCanonicalMetric.jl
- src/manifolds/StiefelEuclideanMetric.jl
- src/manifolds/StiefelSubmersionMetric.jl
- test/manifolds/stiefel.jl
This PR makes several improvements to `log` implementations for Stiefel for various metrics, following up after #535:
- Add `log!` for `EuclideanMetric`, which just calls `log!` for `StiefelSubmersionMetric`. This approach is taken because the benchmark in the submersion metric paper (https://arxiv.org/abs/2103.12046) showed that this algorithm was fastest for the Euclidean metric.
- Speed up `log!` for `CanonicalMetric`. This is done by:
- Replacing the view of the Q factor in the final line with an explicit slice. This drastically speeds up the function, since the view approach elementwise computes the entries of the Q factor, which is much slower than computing them all at once.
- ~Removing the Procrustes pre-processing. I'm not certain what this does. It's absent from the formulation …
> Improvements to log for Stiefel

- Project.toml
- src/Manifolds.jl
- src/manifolds/KendallsShapeSpace.jl
- src/manifolds/QuotientManifold.jl
- test/manifolds/shape_space.jl
The horizontal and vertical component functions are defined generically. I've fixed dimension calculation in over-dimensioned cases but there might still be some other issues. Norm and inner on Kendall's shape space uses horizontal component calculation to return correct results.
> Add horizontal and vertical component calculation to Kendall's shape space

- .gitignore
- Project.toml
- test/recipes.jl
Plots.jl has deprecated its PyPlot backend in favor of PythonPlot. This PR switches to using PythonPlot in our tests.
> Using PythonPlot instead of PyPlot in tests

- Project.toml
- src/manifolds/Grassmann.jl
- test/manifolds/grassmann.jl
Main reason – it defaulted to exp/parallel transport, which do not exist in Stiefel representation.
> Fix defaults on Grassmann

- Project.toml
- src/groups/rotation_action.jl
- src/manifolds/SymmetricPositiveDefinite.jl
- src/manifolds/SymmetricPositiveDefiniteGeneralizedBuresWasserstein.jl
- test/manifolds/symmetric_positive_definite.jl
A small bugfix. `eigvals` returns complex eigenvalues in the provided test case, which are not comparable to 0. This, also, should be faster.
> Fix check_point for SPD

- test/ambiguities.jl
It looks like https://github.com/JuliaManifolds/ManifoldsBase.jl/pull/155 caused some new harmless ambiguities in the `convert` function. This PR bumps how many are allowed.
> Bump allowed ambiguities

- Project.toml
- src/manifolds/ProbabilitySimplex.jl
- test/manifolds/probability_simplex.jl
I've checked a few sources, primarily Ay's book, and I think that's all that has to be adjusted. That boundary is still weird because its tangent space effectively doesn't allow for tangent vectors pointing into the simplex. Pushforward of the map between sphere and probability simplex simply zeroes these components.
> Add optional boundary to probability simplex

- .gitignore
- Project.toml
- benchmark/benchmarks.jl
- docs/src/manifolds/symmetricpositivedefinite.md
- src/Manifolds.jl
- src/deprecated.jl
- src/manifolds/SymmetricPositiveDefinite.jl
- src/manifolds/SymmetricPositiveDefiniteAffineInvariant.jl
- test/manifolds/sphere.jl
- test/manifolds/symmetric_positive_definite.jl
- test/runtests.jl
- test/statistics.jl
- test/test_deprecated.jl
- tutorials/getstarted.jl
use `AffineInvariantMetric` instead. This resolves #527.
I am just not sure the deprecation tests work, it seems one can check for a warning (if tests are run with `depwarn=true` or use `@test_deprecated´ but I can consistently get both to pass and fail. So let's see what the CI likes.
> Deprecate LinearAffineMetric, resolves #527

- src/groups/product_group.jl
An issue I've noticed when working on #609 . The last `isapprox` (for `ProductGroup`) originally took like half a minute to compile for me, with this it's a few seconds. Still too much but at least it's a bit better.
> Reduce TTFisapprox on ProductGroup

- Project.toml
- src/groups/product_group.jl
- src/groups/semidirect_product_group.jl
- src/groups/special_euclidean.jl
- src/manifolds/Circle.jl
- src/manifolds/ProductManifold.jl
- src/manifolds/VectorBundle.jl
- src/product_representations.jl
- test/groups/metric.jl
- test/groups/semidirect_product_group.jl
- test/groups/special_euclidean.jl
- test/manifolds/circle.jl
- test/manifolds/power_manifold.jl
- test/manifolds/product_manifold.jl
Resolves one of the issues raised in #609 .
This should be only slightly breaking so I don't think an actual breaking release is necessary.
> Make ArrayPartition default instead of ProductRepr

- Project.toml
- src/Manifolds.jl
- src/groups/group.jl
- src/manifolds/Circle.jl
- src/manifolds/Euclidean.jl
- src/manifolds/Hyperbolic.jl
- src/manifolds/ProductManifold.jl
- src/manifolds/Sphere.jl
- test/groups/special_orthogonal.jl
- test/manifolds/circle.jl
- test/manifolds/euclidean.jl
- test/manifolds/hyperbolic.jl
- test/manifolds/product_manifold.jl
- test/manifolds/sphere.jl
- test/utils.jl
See here: https://github.com/JuliaManifolds/ManifoldDiff.jl/issues/20
> Move ManifoldDiff extension here

- .gitignore
- Project.toml
- accuracy/Hyperboloid.qmd
- accuracy/Project.toml
- accuracy/Readme.md
- accuracy/_quarto.yml
- src/manifolds/HyperbolicHyperboloid.jl
Replaces distance, exponential, and logarithmic maps to more numerically stable versions, as per the Matlab Manopt version.
> Stable hyperbolic functions

- Project.toml
- src/manifolds/GeneralUnitaryMatrices.jl
- test/manifolds/rotations.jl
Fixes #635 and some related issues.
> Fix `Rotations(1)`

- Project.toml
- src/manifolds/VectorBundle.jl
A small cleanup plus making them a bit more extensible.
> Small cleanup of vector bundles

- Project.toml
- src/groups/special_euclidean.jl
- src/manifolds/GeneralUnitaryMatrices.jl
- test/groups/special_euclidean.jl
See https://github.com/JuliaRobotics/IncrementalInference.jl/issues/1546#issuecomment-1749587523 for explanation.
> Improve performance of selected operations on SE(n)

- Project.toml
- src/groups/semidirect_product_group.jl
- src/groups/special_euclidean.jl
- test/groups/special_euclidean.jl
- Added get_coordinates and get_vector specialized dispatches: vee and hat do not always seem to dispatch without allocations and there are places where we use get_vector/coordinates.
- Not only SVector for coordinates: we take the coordinates from a larger vector in some places.
> Add more SE2 and SE3 performance dispatches

- src/groups/rotation_action.jl
Minor discrepancy in `ColumnwiseMultiplicationAction` type doc.
> doc for ColumnwiseMultiplicationAction type

- NEWS.md
- Project.toml
- ext/ManifoldsBoundaryValueDiffEqExt.jl
This may resolve the never-ending solving problem on BoundaryValueDiffEq v5. Resolves #664 . Replaces #657 .
> Update for BoundaryValueDiffEq v5

- NEWS.md
- Project.toml
- src/manifolds/Circle.jl
- test/manifolds/circle.jl
See https://github.com/JuliaManifolds/Manopt.jl/pull/335#issuecomment-1869083300 .
> Fix an edge case of PT on Circle

- NEWS.md
- Project.toml
- src/groups/GroupManifold.jl
- src/groups/general_unitary_groups.jl
- src/groups/power_group.jl
- src/manifolds/ProbabilitySimplexEuclideanMetric.jl
- src/manifolds/Unitary.jl
- src/utils.jl
- test/manifolds/probability_simplex.jl
- test/manifolds/unitary_matrices.jl
This small fix could even reduce other Lie groups random implementations
> More random randomness on random (no actually all) Lie groups

- .github/workflows/ci.yml
- NEWS.md
- Project.toml
- docs/make.jl
- docs/src/manifolds/grassmann.md
- docs/src/manifolds/hyperrectangle.md
- docs/src/references.bib
- src/Manifolds.jl
- src/manifolds/Euclidean.jl
- src/manifolds/Hyperrectangle.jl
- test/manifolds/circle.jl
- test/manifolds/hyperrectangle.jl
- test/manifolds/sphere.jl
- test/manifolds/symmetric_positive_definite.jl
- test/runtests.jl
Mostly to make Manopt work with box constraints. The trick is just projecting gradients and projection retraction but it's still better than nothing IMO. Activity analysis needs to be done on Manopt's side.
> Hyperrectangle

- NEWS.md
- Project.toml
- docs/src/references.bib
- src/manifolds/Stiefel.jl
- src/manifolds/StiefelEuclideanMetric.jl
- test/manifolds/stiefel.jl
cf. Zimmermann & Stoye https://arxiv.org/abs/2405.02268v1 .
> Implement infectivity radius on Stiefel

- src/manifolds/MetricManifold.jl
- test/ambiguities.jl
Maybe it will fix the CI failure in #728
> Trying to fix FiniteDifferences + SArray failure

- NEWS.md
- Project.toml
- ext/ManifoldsTestExt/tests_general.jl
- src/manifolds/Grassmann.jl
- src/manifolds/GrassmannStiefel.jl
- test/manifolds/grassmann.jl
I recently noticed (p. 171 AMS08), that parallel transport on Grassmann (Stiefel representation) has a closed form in the `_direction` variant. So here is an implementation.
Will add tests the next few days.
> Implement and document parallel transport on Grassmann.

- NEWS.md
- src/manifolds/Symplectic.jl
- src/manifolds/SymplecticStiefel.jl
This just fix three small typos.
> fix a few typos.

- src/groups/group.jl
The order in description and equations was confusing
> `translate_diff` documentation clarification

- NEWS.md
- ext/ManifoldsOrdinaryDiffEqExt.jl
- src/manifolds/ConnectionManifold.jl
- test/metric.jl
Fixes #744 and fixes #740. Also add some new tests that fail without the fix for #744.
> Fix solve_exp_ode not updating position

- NEWS.md
- Project.toml
- src/groups/GroupManifold.jl
- test/groups/groups_general.jl
The default representation for GroupManifold is `LeftInvariantRepresentation`, this ensures backward compatibility with previous versions of `Manifolds.jl`
> GroupManifold accepts two arguments

- docs/src/features/atlases.md
Typo can be seen on https://juliamanifolds.github.io/Manifolds.jl/stable/features/atlases.html
Looks like a missing `\` so I added it, though I haven't previewed if that does, in fact, fix it.
> Fix typo in atlases documentation

- NEWS.md
- src/groups/general_unitary_groups.jl
- test/groups/general_unitary_groups.jl
After some computations, there are numerical errors in the elements of $`\mathfrak{so}(2)`$. This PR ensures that even after errors, the Lie bracket is exactly zero.
> Lie bracket is zero on so(2)

- NEWS.md
- Project.toml
- docs/make.jl
- docs/src/index.md
- docs/src/manifolds/invertible.md
- docs/styles/config/vocabularies/Manifolds/accept.txt
- src/Manifolds.jl
- src/manifolds/InvertibleMatrices.jl
- test/manifolds/invertible_matrices.jl
- test/runtests.jl
This is merely for completeness and it makes a few steps in LieGroups.jl a bit easier/generic.
> introduce invertible matrices (merely for completeness)

- .github/workflows/ci.yml
- .github/workflows/documenter.yml
- NEWS.md
- Project.toml
- ext/ManifoldsBoundaryValueDiffEqExt.jl
- ext/ManifoldsDistributionsExt/ManifoldsDistributionsExt.jl
- ext/ManifoldsHybridArraysExt.jl
- ext/ManifoldsNLsolveExt.jl
- ext/ManifoldsOrdinaryDiffEqDiffEqCallbacksExt.jl
- ext/ManifoldsOrdinaryDiffEqExt.jl
- ext/ManifoldsRecipesBaseExt.jl
- ext/ManifoldsRecursiveArrayToolsExt/ManifoldsRecursiveArrayToolsExt.jl
- ext/ManifoldsTestExt/ManifoldsTestExt.jl
- src/Manifolds.jl
- Bump Julia compat in `Project.toml` from 1.6 to 1.10
- Bump Manifolds version to v0.10.8
- Update CI to run on `lts`, `1` (stable) and `pre` (pre-release)
- Remove Requires and its extension shenanigans
> Bump Julia compat to 1.10

- NEWS.md
- Project.toml
- docs/src/misc/internals.md
- src/Manifolds.jl
- src/manifolds/CholeskySpace.jl
- src/manifolds/SymmetricPositiveDefinite.jl
- src/manifolds/SymmetricPositiveDefiniteLogCholesky.jl
- test/manifolds/cholesky_space.jl
- test/manifolds/symmetric_positive_definite.jl
Some stuff that I needed for Kalman filters.
Also `get_parameter_arg` should probably go in more places.
> Bases for CholeskySpace and LogCholesky metric

- NEWS.md
- Project.toml
- src/manifolds/Rotations.jl
This could be further optimized but at least we won't call generic matrix `exp` on rotations in 3D.
> Improved implementation of PT on Rotations(3)

- .github/workflows/nightly.yml
- NEWS.md
- src/Manifolds.jl
- src/manifolds/GrassmannStiefel.jl
- src/manifolds/Hyperbolic.jl
Just saw that a super type was wrong – this can wait for the next larger thing to be fixed I think, but awe could maybe merge it already to master.
> fix supertype of a few tangent vectors that were `<: AbstractManifoldPoint`

- .github/workflows/ci.yml
MacOS ARM does not have x86 so you're doing bad things here https://github.com/JuliaLang/julia/issues/55878 and https://github.com/julia-actions/setup-julia/pull/300
> Remove incorrect architecture choice in ci.yml
